frameworks:
  entries:
    - lib: actionpack
      variants:
        - label: default
          rubies: all
        - label: rack-2
          rack_requirement: '~> 2.0'
          repo_pre_steps: bundle install
          allow_failure: false
          rubies: default
        - label: rack-3-0
          rack_requirement: '~> 3.0.0'
          repo_pre_steps: bundle install
          allow_failure: false
          rubies: default
          rails_version: '>= 7.1'
        - label: rack-head
          rack_requirement: head
          repo_pre_steps: "rm Gemfile.lock && bundle install"
          allow_failure: true
          rubies: default
          rails_version: '>= 7.1'
        - label: isolated
          task: 'test:isolated'
          rubies: default

    - lib: activerecord
      variants:
        - label: mysql2
          task: 'db:mysql:rebuild mysql2:test'
          rubies: all
          repo_pre_steps: &mysql_init |
            mysql -hmysql -uroot -e "
              CREATE USER IF NOT EXISTS 'rails'@'%' IDENTIFIED BY '';
              GRANT ALL PRIVILEGES ON activerecord_unittest.* TO 'rails'@'%';
              GRANT ALL PRIVILEGES ON activerecord_unittest2.* TO 'rails'@'%';
              CREATE DATABASE IF NOT EXISTS activerecord_unittest DEFAULT CHARACTER SET utf8mb4;
              CREATE DATABASE IF NOT EXISTS activerecord_unittest2 DEFAULT CHARACTER SET utf8mb4;
            "
        - label: mysql2-mariadb
          task: 'db:mysql:rebuild mysql2:test'
          repo_pre_steps: *mysql_init
          mysql_image: mariadb:11.4
          rubies: default
        - label: mysql2-mysql-5-7
          task: 'db:mysql:rebuild mysql2:test'
          repo_pre_steps: *mysql_init
          mysql_image: mysql:5.7
          rubies: default
        - label: mysql2-prepared-statements
          task: 'db:mysql:rebuild mysql2:test'
          repo_pre_steps: *mysql_init
          mysql_prepared_statements: 'true'
          rubies: default
        - label: postgresql
          task: 'db:postgresql:rebuild postgresql:test'
          rubies: all
        - label: sqlite3
          task: 'sqlite3:test'
          rubies: all
        - label: sqlite3-mem
          task: 'sqlite3_mem:test'
          rubies: default
        - label: trilogy
          task: 'db:mysql:rebuild trilogy:test'
          repo_pre_steps: *mysql_init
          rubies: all
        - label: trilogy-mariadb
          task: 'db:mysql:rebuild trilogy:test'
          repo_pre_steps: *mysql_init
          mysql_image: mariadb:11.4
          rubies: default
        - label: trilogy-mysql-5-7
          task: 'db:mysql:rebuild trilogy:test'
          repo_pre_steps: *mysql_init
          mysql_image: mysql:5.7
          rubies: default
          rails_version: '>= 7.1'
        - label: mysql2-isolated
          task: 'db:mysql:rebuild mysql2:isolated_test'
          repo_pre_steps: *mysql_init
          rubies: default
        - label: postgresql-isolated
          task: 'db:postgresql:rebuild postgresql:isolated_test'
          rubies: default
        - label: sqlite3-isolated
          task: 'sqlite3:isolated_test'
          rubies: default
        - label: trilogy-isolated
          task: 'db:mysql:rebuild trilogy:isolated_test'
          repo_pre_steps: *mysql_init
          rails_version: '>= 7.1'
          rubies: default

    - lib: actioncable
      variants:
        - label: default
          repo_pre_steps: bundle exec rake -f activerecord/Rakefile db:postgresql:rebuild
          nodejs: true
          rubies: all
        - label: integration
          task: 'test:integration'
          rubies: all

    - lib: actionmailbox
      variants:
        - label: default
          rubies: all

    - lib: actionmailer
      variants:
        - label: default
          rubies: all
        - label: isolated
          task: 'test:isolated'
          rubies: default

    - lib: actiontext
      variants:
        - label: default
          nodejs: true
          rubies: all

    - lib: actionview
      variants:
        - label: default
          rubies: all
        - label: isolated
          task: 'test:isolated'
          rubies: default

    - lib: activejob
      variants:
        - label: default
          rubies: all
        - label: integration
          task: 'test:integration'
          allow_failure: true
          rubies: all
        - label: isolated
          task: 'test:isolated'
          rubies: default

    - lib: activemodel
      variants:
        - label: default
          rubies: all
        - label: isolated
          task: 'test:isolated'
          rubies: default

    - lib: activestorage
      variants:
        - label: default
          nodejs: true
          rubies: all

    - lib: activesupport
      variants:
        - label: default
          rubies: all
        - label: isolated
          task: 'test:isolated'
          rubies: default
          services:
            memcached:
              image: memcached:1.6-alpine
              ports: ['11211:11211']

    - lib: guides
      variants:
        - label: default
          rubies: all

    - lib: railties
      shards: 12
      variants:
        - label: default
          rubies: all
        - label: rack-2
          rack_requirement: '~> 2.0'
          repo_pre_steps: bundle install
          rubies: default
        - label: rack-3-0
          rack_requirement: '~> 3.0.0'
          repo_pre_steps: bundle install
          rubies: default
          rails_version: '>= 7.1'
        - label: rack-head
          rack_requirement: head
          repo_pre_steps: "rm Gemfile.lock && bundle install"
          allow_failure: true
          rails_version: '>= 7.1'
          rubies: default
