name: Setup Rails CI environment
description: Install optional system dependencies, configure Ruby, and install gems.
inputs:
  bundler-cache:
    description: Whether to enable Bundler caching.
    required: false
    default: 'false'
  bundle-install:
    description: Run "bundle install" after setting up Ruby.
    required: false
    default: 'true'
  bundle-working-directory:
    description: Directory in which to run "bundle install".
    required: false
    default: '.'
runs:
  using: composite
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: none
        bundler-cache: ${{ inputs.bundler-cache }}
    - if: ${{ inputs.bundle-install != 'false' }}
      shell: bash
      working-directory: ${{ inputs.bundle-working-directory }}
      run: bundle install --jobs 4 --retry 3
