name: Load Rails CI Configuration

on:
  workflow_call:
    inputs:
      source-repo:
        description: Repository containing the Rails source to test
        required: false
        type: string
      source-ref:
        description: Git ref of the Rails source to test
        required: false
        type: string
    outputs:
      frameworks:
        description: JSON representation of the frameworks configuration
        value: ${{ jobs.load-config.outputs.frameworks }}
      ruby-supported:
        description: JSON array of supported Ruby versions
        value: ${{ jobs.load-config.outputs.ruby-supported }}
      ruby-default:
        description: Default Ruby version
        value: ${{ jobs.load-config.outputs.ruby-default }}

jobs:
  load-config:
    name: Load Config
    runs-on: ubuntu-latest
    outputs:
      frameworks: ${{ steps.extract.outputs.frameworks }}
      ruby-supported: ${{ steps.extract.outputs.ruby-supported }}
      ruby-default: ${{ steps.extract.outputs.ruby-default }}
    steps:
      - name: Checkout CI utilities
        uses: actions/checkout@v4
        with:
          repository: aedipamoss/child
          ref: new
          path: rails-ci

      - name: Checkout Rails source
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.source-repo }}
          ref: ${{ inputs.source-ref }}
          path: source

      - name: Parse config
        id: extract
        run: |
          ruby "${{ github.workspace }}/rails-ci/.github/scripts/parse-rails-ci-config-new.rb" \
            "${{ github.workspace }}/rails-ci/.github/rails-ci-config-new.yml" \
            "${{ github.workspace }}/source"

      - name: Show extracted config
        run: |
          echo "Frameworks config:"
          echo "${{ toJson(steps.extract.outputs.frameworks) }}"
          echo "Ruby supported:"
          echo "${{ toJson(steps.extract.outputs.ruby-supported) }}"
          echo "Ruby default:"
          echo "${{ toJson(steps.extract.outputs.ruby-default) }}"
