name: Load Rails CI Configuration

on:
  workflow_call:
    inputs:
      source-repo:
        description: Repository containing the Rails source to test
        required: false
        type: string
      source-ref:
        description: Git ref of the Rails source to test
        required: false
        type: string

jobs:
  load-config:
    name: Load Config
    runs-on: ubuntu-latest
    outputs:
      frameworks-matrix: ${{ steps.extract.outputs.frameworks-matrix }}
      ruby-supported: ${{ steps.extract.outputs.ruby-supported }}
      ruby-default: ${{ steps.extract.outputs.ruby-default }}

    steps:
      - name: Checkout CI utilities
        uses: actions/checkout@v4
        with:
          repository: aedipamoss/child
          ref: new
          path: rails-ci

      - name: Checkout Rails source
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.source-repo }}
          ref: ${{ inputs.source-ref }}
          path: source

      - name: Parse config
        id: extract
        run: |
          ruby "${{ github.workspace }}/rails-ci/.github/scripts/parse-rails-ci-config-new.rb" \
            "${{ github.workspace }}/rails-ci/.github/rails-ci-config.yml" \
            "${{ github.workspace }}/source"
