# Sample parent workflow demonstrating how to invoke the reusable Rails CI
# workflow from another repository. This workflow is not intended to be used
# directly in production; it exists to showcase the expected contract for
# callers.
name: Proof of Concept Pipeline

on:
  workflow_call:
    inputs:
      head_sha:
        description: Commit SHA to execute against
        required: true
        type: string
      ref:
        description: Git ref to run the Rails build on
        required: false
        type: string
      notes:
        description: Optional notes forwarded to the Rails CI workflow
        required: false
        type: string
      parent_workflow_id:
        description: Identifier for the upstream workflow run
        required: false
        type: string

permissions:
  contents: read

jobs:
  resolve-ref:
    name: Resolve git ref
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.determine.outputs.ref }}
    steps:
      - name: Determine ref
        id: determine
        run: |
          if [ -n "${{ inputs.ref }}" ]; then
            echo "ref=${{ inputs.ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "ref=${{ inputs.head_sha }}" >> "$GITHUB_OUTPUT"
          fi

  trigger-rails-build:
    name: Trigger Rails Build workflow
    needs: resolve-ref
    uses: ./.github/workflows/rails-ci.yml
    with:
      head_sha: ${{ inputs.head_sha }}
      config_ref: ${{ needs.resolve-ref.outputs.ref }}
      notes: ${{ inputs.notes != '' && inputs.notes || format('Triggered by workflow {0}', github.run_id) }}
      parent_workflow_id: ${{ inputs.parent_workflow_id }}
