name: Rails CI Child

on:
  workflow_call:
    inputs:
      parent-workflow-id:
        description: Identifier of the parent workflow run
        required: true
        type: string
      source-repo:
        description: Repository containing the Rails source to test
        required: false
        type: string
      source-ref:
        description: Git ref of the Rails source to test
        required: false
        type: string

jobs:
  load-config:
    name: Load Config
    runs-on: ubuntu-latest
    outputs:
      frameworks: ${{ steps.extract.outputs.frameworks }}
      shards: ${{ steps.extract.outputs.shards }}
      ruby-supported: ${{ steps.extract.outputs.ruby-supported }}
      ruby-default: ${{ steps.extract.outputs.ruby-default }}
    steps:
      - name: Checkout CI utilities
        uses: actions/checkout@v4
        with:
          repository: aedipamoss/child
          ref: main
          path: rails-ci

      - name: Checkout Rails source
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
          ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}
          path: source

      - name: Parse config
        id: extract
        run: |
          ruby "${{ github.workspace }}/rails-ci/.github/scripts/parse-rails-ci-config.rb" \
            "${{ github.workspace }}/rails-ci/.github/rails-ci-config.yml" \
            "${{ github.workspace }}/source"

  actionpack:
    name: Action Pack
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: actionpack
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).actionpack) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  activerecord:
    name: Active Record
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: activerecord
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).activerecord) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  actioncable:
    name: Action Cable
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: actioncable
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).actioncable) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  actionmailbox:
    name: Action Mailbox
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: actionmailbox
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).actionmailbox) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  actionmailer:
    name: Action Mailer
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: actionmailer
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).actionmailer) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  actiontext:
    name: Action Text
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: actiontext
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).actiontext) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  actionview:
    name: Action View
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: actionview
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).actionview) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  activejob:
    name: Active Job
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: activejob
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).activejob) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  activemodel:
    name: Active Model
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: activemodel
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).activemodel) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  activestorage:
    name: Active Storage
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: activestorage
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).activestorage) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  activesupport:
    name: Active Support
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: activesupport
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).activesupport) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  guides:
    name: Guides
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: guides
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).guides) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  railties:
    name: Railties
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: railties
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).railties) }}
      shards: ${{ toJson(fromJson(needs.load-config.outputs.shards).railties) }}
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}
