name: Rails CI Child New

on:
  workflow_call:
    inputs:
      parent-workflow-id:
        description: Identifier of the parent workflow run
        required: true
        type: string
      source-repo:
        description: Repository containing the Rails source to test
        required: false
        type: string
      source-ref:
        description: Git ref of the Rails source to test
        required: false
        type: string

jobs:
  load-config:
    uses: ./.github/workflows/load-config.yml
    with:
      source-repo: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
      source-ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}

  actionpack:
    name: Action Pack
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: actionpack
      matrix-json: ${{ toJson(fromJson(needs.load-config.outputs.frameworks-matrix).frameworks.actionpack) }}

  activerecord:
    name: Active Record
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: activerecord
      matrix-json: ${{ toJson(fromJson(needs.load-config.outputs.frameworks-matrix).frameworks.activerecord) }}

  activesupport:
    name: Active Support
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: activesupport
      matrix-json: ${{ toJson(fromJson(needs.load-config.outputs.frameworks-matrix).frameworks.activesupport) }}

  railties:
    name: Railties
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: railties
      matrix-json: ${{ toJson(fromJson(needs.load-config.outputs.frameworks-matrix).frameworks.railties) }}
