name: Rails CI Child New

on:
  workflow_call:
    inputs:
      parent-workflow-id:
        description: Identifier of the parent workflow run
        required: true
        type: string
      source-repo:
        description: Repository containing the Rails source to test
        required: false
        type: string
      source-ref:
        description: Git ref of the Rails source to test
        required: false
        type: string

jobs:
  load-config:
    name: Load Config
    runs-on: ubuntu-latest
    outputs:
      frameworks: ${{ steps.extract.outputs.frameworks }}
      #ruby-supported: ${{ steps.extract.outputs.ruby-supported }}
      #ruby-default: ${{ steps.extract.outputs.ruby-default }}
    steps:
      - name: Checkout CI utilities
        uses: actions/checkout@v4
        with:
          repository: aedipamoss/child
          ref: new
          path: rails-ci

      - name: Checkout Rails source
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.source-repo != '' && inputs.source-repo || github.repository }}
          ref: ${{ inputs.source-ref != '' && inputs.source-ref || github.sha }}
          path: source

      - name: Parse config
        id: extract
        run: |
          ruby "${{ github.workspace }}/rails-ci/.github/scripts/parse-rails-ci-config-new.rb" \
            "${{ github.workspace }}/rails-ci/.github/rails-ci-config-new.yml" \
            "${{ github.workspace }}/source"

  debug:
    name: Debug Loaded Config
    needs: load-config
    runs-on: ubuntu-latest
    steps:
      - name: Output frameworks config
        run: |
          echo "Frameworks config:"
          echo '${{ needs.load-config.outputs.frameworks }}'
          echo "Action Pack"
          echo '${{ fromJson(needs.load-config.outputs.frameworks).actionpack }}'

  actionpack:
    name: Action Pack
    needs: load-config
    uses: ./.github/workflows/framework.yml
    with:
      framework: actionpack
      matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).actionpack) }}

  #activerecord:
  #  name: Active Record
  #  needs: load-config
  #  uses: ./.github/workflows/framework.yml
  #  with:
  #    framework: activerecord
  #    matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).frameworks.activerecord) }}

  #activesupport:
  #  name: Active Support
  #  needs: load-config
  #  uses: ./.github/workflows/framework.yml
  #  with:
  #    framework: activesupport
  #    matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).frameworks.activesupport) }}

  #railties:
  #  name: Railties
  #  needs: load-config
  #  uses: ./.github/workflows/framework.yml
  #  with:
  #    framework: railties
  #    matrix: ${{ toJson(fromJson(needs.load-config.outputs.frameworks).frameworks.railties) }}
