name: Test Child Workflow Against Rails Main

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write

jobs:
  test-child:
    name: Run
    uses: ./.github/workflows/rails-ci-child.yml
    with:
      parent-workflow-id: ${{ github.run_id }}
      source-repo: rails/rails
      source-ref: main
